Repository ChungBazi/ChungBazi-iOS, pull requests merged in 2025-01, with the labels that each got.

#2 Chore #1 - 깃 기본 세팅
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/default-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
Labels: Chore 📂

#7 [Feat] #6 네비바 및 탭바 구현
  ChungBazi/ChungBazi.xcodeproj/project.pbxproj
  ChungBazi/ChungBazi/App/SceneDelegate.swift
  ChungBazi/ChungBazi/Info.plist
  ChungBazi/ChungBazi/Resources/Assets.xcassets/d_day_pocket/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/d_day_pocket/d_day_blue200.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/d_day_pocket/d_day_blue200.imageset/d_day_blue200.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/d_day_pocket/d_day_blue700.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/d_day_pocket/d_day_blue700.imageset/d_day_blue700.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/d_day_pocket/d_day_blue900.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/d_day_pocket/d_day_blue900.imageset/d_day_blue900.svg
  ChungBazi/ChungBazi/Sources/Common/Components/Labels.swift
  ChungBazi/ChungBazi/Sources/Common/Components/NavigationBar.swift
  ChungBazi/ChungBazi/Sources/Common/Extension/UIImage+Extensions.swift
  ChungBazi/ChungBazi/Sources/Common/Extension/UILabel+Extensions.swift
  ChungBazi/ChungBazi/Sources/Common/Extension/UIView+Extension.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Models/Untitled20.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Models/Untitled8.swift
  ChungBazi/ChungBazi/Sources/Feature/MainTabBar/MainTabBarController.swift
Labels: Feature ✨

#16 Feat #15 - 마이페이지 구현
  .gitignore
  ChungBazi/ChungBazi.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ChungBazi/ChungBazi/Resources/Assets.xcassets/Colorchip/etc/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/Colorchip/etc/buttonAccent.colorset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/move_icon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/move_icon.imageset/move_icon.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/myCharacter_icon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/myCharacter_icon.imageset/myCharacter_icon.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/reward_color_icon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/reward_color_icon.imageset/Vector.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/reward_icon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/reward_icon.imageset/reward_icon.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/trash_icon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/trash_icon.imageset/trash_icon.svg
  ChungBazi/ChungBazi/Sources/Common/Components/CustomAlert.swift
  ChungBazi/ChungBazi/Sources/Common/Components/KeyboardHandler.swift
  ChungBazi/ChungBazi/Sources/Common/Components/Labels.swift
  ChungBazi/ChungBazi/Sources/Common/Extension/UIButton+Extensions.swift
  ChungBazi/ChungBazi/Sources/Feature/MainTabBar/MainTabBarController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/Models/ProfileModel.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/ViewController/ProfileViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/Views/ProfileMyReward.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/Views/ProfileTableCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/Views/ProfileView.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Edit/ViewController/ProfileEditViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Edit/Views/ProfileEditView.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Models/Untitled14.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/ViewControllers/MyCharacterViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/ViewControllers/MypageViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Views/Untitled15.swift
Labels: Design 🎨, Feature ✨

#18 Design/#8 - 커스텀 드롭다운 구현 및 userSurvey 뷰 구현 완료
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/dropdown_icon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/dropdown_icon.imageset/stat_minus_1.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/dropup_icon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/dropup_icon.imageset/stat_minus_1.svg
  ChungBazi/ChungBazi/Sources/Common/Components/CustomActiveButton.swift
  ChungBazi/ChungBazi/Sources/Common/Components/CustomButton.swift
  ChungBazi/ChungBazi/Sources/Common/Components/CustomDropDownView.swift
  ChungBazi/ChungBazi/Sources/Common/Components/CustomDropdown.swift
  ChungBazi/ChungBazi/Sources/Common/Utilities/Constants.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetEducationViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetEmploymentStatusViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetIncomeLevelViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetInterestViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetPlusViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetRegionViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/StartSurveyViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/Views/BasicSurveyView.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/Views/CheckCollectionViewCell.swift
Labels: Design 🎨, Feature ✨

#21 Design/#19 - 알림 분류 버튼, 알림 리스트 컬렉션뷰 구현 -> 뷰 구현 완료
  ChungBazi/ChungBazi.xcodeproj/project.pbxproj
  ChungBazi/ChungBazi/Resources/Assets.xcassets/alarm/alarm_calendar_icon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/alarm/alarm_calendar_icon.imageset/캘린더.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/alarm/alarm_community_icon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/alarm/alarm_community_icon.imageset/커뮤니티.svg
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/AlarmViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/BaseTabBarController.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/Views/AlarmListCollecionViewCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/Views/Untitled11.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/FinishSurveyViewController.swift
Labels: Design 🎨
