Repository ChungBazi/ChungBazi-iOS, pull requests merged in 2025-02, with the labels that each got.

#26 Feat/#20 - 지금까지 스웨거에 반영된 API 세팅
  ChungBazi/ChungBazi.xcodeproj/project.pbxproj
  ChungBazi/ChungBazi/App/AppDelegate.swift
  ChungBazi/ChungBazi/App/SceneDelegate.swift
  ChungBazi/ChungBazi/ChungBazi.entitlements
  ChungBazi/ChungBazi/GoogleService-Info.plist
  ChungBazi/ChungBazi/Info.plist
  ChungBazi/ChungBazi/Sources/Feature/Auth/Views/SelectLoginView.swift
  ChungBazi/ChungBazi/Sources/Network/Auth/Endpoints/AuthEndpoints.swift
  ChungBazi/ChungBazi/Sources/Network/Auth/Request/AuthRequestDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Auth/Response/AuthResponseDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Auth/Services/AuthService.swift
  ChungBazi/ChungBazi/Sources/Network/Calendar/Endpoints/CalendarEndpoints.swift
  ChungBazi/ChungBazi/Sources/Network/Calendar/Request/CalendarRequestDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Calendar/Response/CalendarResponseDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Calendar/Services/CalendarService.swift
  ChungBazi/ChungBazi/Sources/Network/Cart/Endpoints/CartEndpoints.swift
  ChungBazi/ChungBazi/Sources/Network/Cart/Request/CartRequestDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Cart/Response/CartResponseDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Cart/Services/CartService.swift
  ChungBazi/ChungBazi/Sources/Network/Common/Domain.swift
  ChungBazi/ChungBazi/Sources/Network/Common/Extensions/NetworkManager+Extension.swift
  ChungBazi/ChungBazi/Sources/Network/Common/NetworkError.swift
  ChungBazi/ChungBazi/Sources/Network/Common/Plugins/CookiePlugin.swift
  ChungBazi/ChungBazi/Sources/Network/Common/Protocols/NetworkManager+Protocol.swift
  ChungBazi/ChungBazi/Sources/Network/Common/Response/CommonReponseDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Community/Endpoints/CommunityEndpoints.swift
  ChungBazi/ChungBazi/Sources/Network/Community/Request/CommunityRequestDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Community/Response/CommunityResponseDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Community/Services/CommunityService.swift
  ChungBazi/ChungBazi/Sources/Network/Notification/Endpoints/NotificationEndpoints.swift
  ChungBazi/ChungBazi/Sources/Network/Notification/Request/NotificationRequestDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Notification/Response/NotificationResponseDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Notification/Services/NotificationService.swift
  ChungBazi/ChungBazi/Sources/Network/Policy/Endpoints/PolicyEndpoints.swift
  ChungBazi/ChungBazi/Sources/Network/Policy/Request/PolicyRequestDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Policy/Response/PolicyResponseDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Policy/Services/PolicyService.swift
  ChungBazi/ChungBazi/Sources/Network/Untitled4.swift
  ChungBazi/ChungBazi/Sources/Network/User/Endpoints/UserEndpoints.swift
  ChungBazi/ChungBazi/Sources/Network/User/Request/UserRequestDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/User/Response/UserResponseDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/User/Services/UserService.swift
Labels: Chore 📂, Feature ✨

#29 Design/#25 홈 화면 디자인 수정
  ChungBazi/ChungBazi/Sources/Common/Components/NavigationBar.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/HomeViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/Views/CategoryButton.swift
  ChungBazi/ChungBazi/Sources/Feature/Search/ViewControllers/SearchResultViewController.swift
Labels: Design 🎨

#27 Feat/#24 - 카카오 로그인 및 사용자 정보 등록 api 연결
  ChungBazi/ChungBazi/Info.plist
  ChungBazi/ChungBazi/Resources/Assets.xcassets/alarm/alarm_calendar_icon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/alarm/alarm_calendar_icon.imageset/calendar.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/alarm/alarm_community_icon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/alarm/alarm_community_icon.imageset/community.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/dropdown_icon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/dropup_icon.imageset/Contents.json
  ChungBazi/ChungBazi/Sources/Feature/Auth/Models/KakaoAuthVM.swift
  ChungBazi/ChungBazi/Sources/Feature/Auth/ViewControllers/FinishLoginViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Auth/ViewControllers/SelectLoginTypeViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/Models/Untitled18.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/Models/UserInfoDataManager.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetEducationViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetEmploymentStatusViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetIncomeLevelViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetInterestViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetPlusViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetRegionViewController.swift
  ChungBazi/ChungBazi/Sources/Network/Auth/Endpoints/AuthEndpoints.swift
  ChungBazi/ChungBazi/Sources/Network/Common/Domain.swift
  ChungBazi/ChungBazi/Sources/Network/User/Endpoints/UserEndpoints.swift
  ChungBazi/ChungBazi/Sources/Network/User/Services/UserService.swift
Labels: Feature ✨

#33 Fix/#32 - 이미지 수정 및 네비 root 뷰 수정
  ChungBazi/ChungBazi/Resources/Assets.xcassets/alarm/alarm_calendar_icon.imageset/calendar.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/alarm/alarm_community_icon.imageset/community.svg
  ChungBazi/ChungBazi/Sources/Feature/Auth/ViewControllers/FinishLoginViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/FinishSurveyViewController.swift
Labels: Fix 🔨

#35 #34 Chore: afg regular 폰트 추가
  ChungBazi/ChungBazi/Info.plist
  ChungBazi/ChungBazi/Resources/Fonts/AssacomFreeGothic.otf
  ChungBazi/ChungBazi/Sources/Common/Extension/UIFont+Extensions.swift
Labels: Chore 📂

#38 #36 Fix: "청바지" 단어 폰트 수정 및 커스텀 드롭다운 파라미터 수정
  ChungBazi/ChungBazi/Sources/Common/CommonView/LogoWithTitleView.swift
  ChungBazi/ChungBazi/Sources/Common/Components/CustomDropDownView.swift
  ChungBazi/ChungBazi/Sources/Common/Components/CustomDropdown.swift
  ChungBazi/ChungBazi/Sources/Feature/Auth/Views/SelectLoginView.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetEducationViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetEmploymentStatusViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetIncomeLevelViewController.swift
Labels: Fix 🔨

#41 Feat/#39 - 알림 관련 API 연결
  ChungBazi/ChungBazi.xcodeproj/project.pbxproj
  ChungBazi/ChungBazi/App/AppDelegate.swift
  ChungBazi/ChungBazi/App/SceneDelegate.swift
  ChungBazi/ChungBazi/Resources/Assets.xcassets/alarm/alarm_reward_icon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/alarm/alarm_reward_icon.imageset/alarm_reward_icon.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/plusCircle.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/plusCircle.imageset/plusCircle.svg
  ChungBazi/ChungBazi/Sources/Common/Components/CustomAlert.swift
  ChungBazi/ChungBazi/Sources/Common/Extension/UIButton+Extensions.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/Basic/ViewController/CalenderViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/Basic/Views/CalendarView.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/Detail/Model/CalendarDetailModel.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/Detail/ViewController/CalendarDetailViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/Detail/Views/CalendarDetailDocumentListCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/Detail/Views/CalendarDetailDocumentListView.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/PolicyList/Views/CalendarPolicyListCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/PolicyList/Views/CalendarPolicyListView.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/Models/AlarmModel.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/AlarmViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/Views/AlarmListCollecionViewCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/Models/ProfileModel.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/ViewController/ProfileViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/Views/ProfileTableCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/Views/ProfileView.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Edit/ViewController/ProfileEditViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Edit/Views/ProfileEditView.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/NotificationSettings/Models/NotificationSettingModel.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/NotificationSettings/ViewController/ProfileNotificationSettingsViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/NotificationSettings/Views/ProfileNotificationSettingsView.swift
  ChungBazi/ChungBazi/Sources/Network/Notification/Endpoints/NotificationEndpoints.swift
  ChungBazi/ChungBazi/Sources/Network/Notification/Request/NotificationRequestDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Notification/Response/NotificationResponseDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Notification/Services/NotificationService.swift
Labels: Feature ✨

#43 Feat/#40 장바구니화면 구현
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/trash_icon.imageset/trash_icon.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/x_icon.imageset/x_icon.svg
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/CartViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/Views/DottedLineView.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/Views/PolicyCardViewCell.swift
Labels: Design 🎨, Feature ✨

#45 Feat/#24 - Auth 관련 api 모두 연결
  ChungBazi/ChungBazi/Sources/Feature/Auth/ViewControllers/FinishLoginViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Auth/ViewControllers/SelectLoginTypeViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Auth/ViewControllers/SplashViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/ViewController/ProfileViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/FinishSurveyViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/StartSurveyViewController.swift
  ChungBazi/ChungBazi/Sources/Network/Auth/Endpoints/AuthEndpoints.swift
  ChungBazi/ChungBazi/Sources/Network/Auth/Services/AuthService.swift
  ChungBazi/ChungBazi/Sources/Network/Common/Extensions/NetworkManager+Extension.swift
  ChungBazi/ChungBazi/Sources/Network/Common/NetworkError.swift
Labels: Feature ✨

#44 Feat/#23 정책상세보기 화면 구현
  ChungBazi/ChungBazi.xcodeproj/project.pbxproj
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/expand_icon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/expand_icon.imageset/expand_icon.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/share_icon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/etc/share_icon.imageset/share_icon.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/policy/poster_example.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/policy/poster_example.imageset/poster_example.svg
  ChungBazi/ChungBazi/Sources/Common/Components/NavigationBar.swift
  ChungBazi/ChungBazi/Sources/Common/Extension/UIImage+Extensions.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/CartViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/RecommendViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/Models/PolicyData.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/Models/PolicyItem.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/Models/PolicyModel.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/ViewControllers/CategoryPolicyViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/ViewControllers/ExpandImageViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/ViewControllers/PolicyDetailViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/Views/CustomAlertView.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/Views/PolicyView.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/Views/PosterView.swift
  ChungBazi/ChungBazi/Sources/Feature/Search/ViewControllers/SearchResultViewController.swift
Labels: Design 🎨, Feature ✨

#48 Feat #31 커뮤니티 화면 구현
  ChungBazi/ChungBazi/Resources/Assets.xcassets/community/sendIcon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/community/sendIcon.imageset/sendIcon.svg
  ChungBazi/ChungBazi/Sources/Common/Components/KeyboardHandler.swift
  ChungBazi/ChungBazi/Sources/Common/Components/UIWrapStackView.swift
  ChungBazi/ChungBazi/Sources/Common/Utilities/Constants.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Basic/Views/CommunityPostListCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Basic/Views/CommunityView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Model/CommunityDetailModel.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/ViewController/CommunityDetailViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailCommentAuthorProfileView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailPostAuthoreProfileView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailPostView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Search/ViewController/CommunitySearchViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Search/Views/CommunitySearchPopularKeywoardsView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Search/Views/CommunitySearchView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Write/ViewController/CommunityWriteViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Write/Views/CommunityWritePhotoCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Write/Views/CommunityWriteView.swift
  ChungBazi/ChungBazi/Sources/Network/Community/Services/CommunityService.swift
Labels: Feature ✨, Fix 🔨

#49 Fix #30 서류 체크리스트 구현
  ChungBazi/ChungBazi/Sources/Feature/Calender/Detail/Views/CalendarDetailDocumentListCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/Detail/Views/CalendarDetailDocumentListView.swift
Labels: Fix 🔨

#52 Design/#47
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/HomeViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/RecommendViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/Views/CategoryButton.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/ViewControllers/CategoryPolicyViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Search/ViewControllers/SearchResultViewController.swift
Labels: Design 🎨

#53 Feat/#42 - 프로필 캐릭터 수정 뷰 구현
  ChungBazi/ChungBazi/Resources/Assets.xcassets/MyPage/Character/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/MyPage/Character/LEVEL_1.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/MyPage/Character/LEVEL_1.imageset/LEVEL_1.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/MyPage/MyCharacter/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/MyPage/MyCharacter/confetti.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/MyPage/MyCharacter/confetti.imageset/confetti.svg
  ChungBazi/ChungBazi/Sources/Common/Components/CustomAlertWithOneBtn.swift
  ChungBazi/ChungBazi/Sources/Common/Components/NavigationBar.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Basic/ViewController/CommunityViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Basic/Views/CommunityPostListCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/Models/ProfileModel.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/ViewController/MyCharacterViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/ViewController/ProfileViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/Views/ProfileView.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Edit/Models/UserProfileManager.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Edit/ViewController/CharacterEditViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Edit/ViewController/ProfileEditViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Edit/Views/CharacterEditCollectionViewCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Edit/Views/ProfileEditView.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetInterestViewController.swift
Labels: Design 🎨

#56 Feat/#42 - 데브에서 충돌나는 거 수정
  ChungBazi/ChungBazi/Sources/Common/Components/NavigationBar.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Basic/ViewController/CommunityViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Edit/ViewController/CharacterEditViewController.swift
Labels: Fix 🔨

#62 Feat/#58 - 커뮤니티 API 연결
  ChungBazi/ChungBazi/Sources/Common/Components/CustomDropdown.swift
  ChungBazi/ChungBazi/Sources/Common/Components/KeyboardHandler.swift
  ChungBazi/ChungBazi/Sources/Common/Extension/DateFormatter+Extensions.swift
  ChungBazi/ChungBazi/Sources/Common/Utilities/Constants.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/Basic/ViewController/CalenderViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/Basic/Views/CalendarView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Basic/Models/CommunityModel.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Basic/ViewController/CommunityViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Basic/Views/CommunityPostListCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Basic/Views/CommunityView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/ViewController/CommunityDetailViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailCommentAuthorProfileView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailCommentCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailPostAuthoreProfileView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailPostView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Search/Views/CommunitySearchView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Write/ViewController/CommunityWriteViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Write/Views/CommunityWritePhotoCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Write/Views/CommunityWriteView.swift
  ChungBazi/ChungBazi/Sources/Network/Calendar/Endpoints/CalendarEndpoints.swift
  ChungBazi/ChungBazi/Sources/Network/Calendar/Request/CalendarRequestDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Calendar/Response/CalendarResponseDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Calendar/Services/CalendarService.swift
  ChungBazi/ChungBazi/Sources/Network/Community/Endpoints/CommunityEndpoints.swift
  ChungBazi/ChungBazi/Sources/Network/Community/Request/CommunityRequestDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Community/Response/CommunityResponseDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Community/Services/CommunityService.swift
Labels: Feature ✨

#65 Feat/#20 - 장바구니, 정책 api 세팅, 유저 정보 조사 로직 변경
  ChungBazi/ChungBazi/App/AppDelegate.swift
  ChungBazi/ChungBazi/Info.plist
  ChungBazi/ChungBazi/Resources/Assets.xcassets/userSurvey/fifthPageLogo.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/userSurvey/fifthPageLogo.imageset/Group 1707478463.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/userSurvey/fifthPageLogo.imageset/fifthPageLogo.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/userSurvey/firstPageLogo.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/userSurvey/firstPageLogo.imageset/firstPageLogo.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/userSurvey/fourthPageLogo.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/userSurvey/fourthPageLogo.imageset/fourthPageLogo.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/userSurvey/sixthPageLogo.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/userSurvey/thirdPageLogo.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/userSurvey/thirdPageLogo.imageset/thirdPageLogo.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/userSurvey/twicePageLogo.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/userSurvey/twicePageLogo.imageset/twicePageLogo.svg
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetIncomeLevelViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/UserSurvey/ViewControllers/SetInterestViewController.swift
  ChungBazi/ChungBazi/Sources/Network/Cart/Endpoints/CartEndpoints.swift
  ChungBazi/ChungBazi/Sources/Network/Cart/Request/CartRequestDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Cart/Response/CartResponseDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Cart/Services/CartService.swift
  ChungBazi/ChungBazi/Sources/Network/Policy/Endpoints/PolicyEndpoints.swift
  ChungBazi/ChungBazi/Sources/Network/Policy/Response/PolicyResponseDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Policy/Services/PolicyService.swift
Labels: Chore 📂, Feature ✨

#67 Fix/#63 UI 수정 사항 수정
  ChungBazi/ChungBazi/Resources/Assets.xcassets/community/likeSelectedIcon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/community/likeSelectedIcon.imageset/likeSelectedIcon.svg
  ChungBazi/ChungBazi/Resources/Assets.xcassets/community/writeIcon.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/community/writeIcon.imageset/writeIcon.svg
  ChungBazi/ChungBazi/Sources/Common/Components/NavigationBar.swift
  ChungBazi/ChungBazi/Sources/Common/Extension/UIViewController+Loading.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/Basic/ViewController/CalenderViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/Basic/Views/CalendarView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Basic/ViewController/CommunityViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Basic/Views/CommunityPostListCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Basic/Views/CommunityView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Model/CommunityDetailModel.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/ViewController/CommunityDetailViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailCommentAuthorProfileView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailCommentCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailPostView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Photo/ViewController/CommunityPhotoViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Photo/Views/CommunityPhotoView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Photo/Views/CommunityPhotoViewerCell.swift
  ChungBazi/ChungBazi/Sources/Feature/MainTabBar/MainTabBarController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/ViewController/ProfileViewController.swift
Labels: Fix 🔨

#68 Feat/#20 - 자잘한 view 오류들 수정
  ChungBazi/ChungBazi/Resources/Assets.xcassets/MyPage/MyCharacter/StarBackground.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/MyPage/MyCharacter/StarBackground.imageset/StarBackground.svg
  ChungBazi/ChungBazi/Sources/Common/CommonView/LogoWithTitleView.swift
Labels: Fix 🔨

#74 Fix/#66 UI 및 로직 수정
  ChungBazi/ChungBazi/Sources/Common/Components/CustomImageView.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/Basic/ViewController/CalenderViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/Basic/Views/CalendarView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Basic/ViewController/CommunityViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Basic/Views/CommunityPostListCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Basic/Views/CommunityView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/ViewController/CommunityDetailViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailCommentAuthorProfileView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailCommentCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailPostAuthoreProfileView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Write/ViewController/CommunityWriteViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Write/Views/CommunityWriteView.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/ViewController/ProfileViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/Views/ProfileView.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Edit/Views/ProfileEditView.swift
  ChungBazi/ChungBazi/Sources/Network/Community/Endpoints/CommunityEndpoints.swift
  ChungBazi/ChungBazi/Sources/Network/Community/Request/CommunityRequestDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/Community/Response/CommunityResponseDTOs.swift
Labels: Fix 🔨

#79 Feat/#73 정책 API 세팅 및 UI 수정
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/CartViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/HomeViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/Views/CartCategoryView.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/Views/CategoryButton.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/Models/PolicyModel.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/ViewControllers/ExpandImageViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/ViewControllers/PolicyDetailViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/Views/CustomAlertView.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/Views/PaddedLabel.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/Views/PolicyCardViewCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/Views/PolicyView.swift
  ChungBazi/ChungBazi/Sources/Feature/Search/ViewControllers/SearchResultViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Search/Views/PopularKeywordCell.swift
  ChungBazi/ChungBazi/Sources/Network/Cart/Response/CartResponseDTOs.swift
Labels: Design 🎨, Feature ✨

#85 Feat/#73 추천탭 및 검색화면 수정
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/CartViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/RecommendViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/ViewControllers/CategoryPolicyViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Search/ViewControllers/SearchResultViewController.swift
  ChungBazi/ChungBazi/Sources/Network/Policy/Response/PolicyResponseDTOs.swift
Labels: Design 🎨, Fix 🔨

#86 #73 홈화면 다이나믹 설정
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/HomeViewController.swift
Labels: Design 🎨

#87 Fix/#81 데모데이 전 수정
  ChungBazi/ChungBazi/Sources/Feature/Calender/Basic/ViewController/CalenderViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/Basic/Views/CalendarView.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/Detail/Views/CalendarDetailDocumentReferenceView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Basic/ViewController/CommunityViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/ViewController/CommunityDetailViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailCommentCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailView.swift
  ChungBazi/ChungBazi/Sources/Feature/MainTabBar/MainTabBarController.swift
  ChungBazi/ChungBazi/Sources/Network/Community/Response/CommunityResponseDTOs.swift
Labels: Fix 🔨

#89 Feat/#78 - 수정할 부분들 처리
  ChungBazi/ChungBazi/App/SceneDelegate.swift
  ChungBazi/ChungBazi/Resources/Assets.xcassets/MyPage/MyCharacter/glowing.imageset/Contents.json
  ChungBazi/ChungBazi/Resources/Assets.xcassets/MyPage/MyCharacter/glowing.imageset/glowing.svg
  ChungBazi/ChungBazi/Sources/Common/Components/CustomDropdown.swift
  ChungBazi/ChungBazi/Sources/Common/Utilities/Constants.swift
  ChungBazi/ChungBazi/Sources/Feature/Auth/Views/SelectLoginView.swift
  ChungBazi/ChungBazi/Sources/Feature/Calender/Detail/ViewController/CalendarDetailViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/Models/AlarmModel.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/AlarmViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/AppInfo/ViewController/ProfileAppInfoViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/AppInfo/ViewController/TermsNConditionsViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/AppInfo/Views/ProfileAppInfoView.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/Basic/Views/MainCharacterView.swift
  ChungBazi/ChungBazi/Sources/Network/Notification/Response/NotificationResponseDTOs.swift
Labels: Feature ✨, Fix 🔨

#90 Fix/#88 데모데이 전 마지막 브랜치
  ChungBazi/ChungBazi/Sources/Common/Utilities/Constants.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/ViewController/CommunityDetailViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Detail/Views/CommunityDetailView.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Write/ViewController/CommunityWriteViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Community/Write/Views/CommunityWriteView.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/AppInfo/ViewController/ProfileAppInfoViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Profile/NotificationSettings/ViewController/ProfileNotificationSettingsViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Search/ViewControllers/SearchResultViewController.swift
Labels: Fix 🔨

#92 Feat/#73 필요한 수정사항 해결
  ChungBazi/ChungBazi/Sources/Common/Components/NavigationBar.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/CartViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/HomeViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Home/ViewControllers/RecommendViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/Models/PolicyData.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/ViewControllers/CategoryPolicyViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/ViewControllers/PolicyDetailViewController.swift
  ChungBazi/ChungBazi/Sources/Feature/Policy/Views/PolicyCardViewCell.swift
  ChungBazi/ChungBazi/Sources/Feature/Search/ViewControllers/SearchResultViewController.swift
  ChungBazi/ChungBazi/Sources/Network/User/Endpoints/UserEndpoints.swift
  ChungBazi/ChungBazi/Sources/Network/User/Response/UserResponseDTOs.swift
  ChungBazi/ChungBazi/Sources/Network/User/Services/UserService.swift
Labels: Design 🎨, Fix 🔨
